### ISSUE TITLE
Original BittBoy

### ISSUE THREAD

**Issue by lucianogardim** [dkodr/SimUI#6]
I couldn't get it to work on my BittBoy 3.5.  It's not PocketGo, it's the original BittBoy.  I downloaded the files and extracted them into the gmenu2x/skins folder (I didn't find a folder with the name you put in the instructions, so I tried the folder that seemed most obvious to me).  I went to the console configuration menu and chose the option, but nothing happens, it assumes the default theme.  Sure it works on the original BittBoy?  I'm using the newest Triforce X firmware, CFW 1.3.3.

**Comment by dkodr** [comment]
This is a theme for [SimpleMenu](https://github.com/fgl82/simplemenu) (as stated on the main page), which means, you'll need SimpleMenu for it to work 😉 Please refer to that repository for installation instructions.
